name             'wordpress-nachum234'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wordpress-nachum234'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'

depends 'php'
depends 'openssl'
depends 'apache2'
depends 'database'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'build-essential'
depends 'tar'
depends 'selinux'
depends 'git'
